### ISSUE TITLE
Version 0.92 crashes with HTMLElement is not defined

### ISSUE THREAD

**Issue by noxxious** [kiteco/vscode-plugin#238]
With VSCode 1.37.0 it crashes with the exception bellow

Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:24:14.598Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.7-1-MANJARO

```[Extension Host] Here is the error stack:  ReferenceError: HTMLElement is not defined
	at Object.module.exports.compact (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:16:17109)
	at n (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:279)
	at Object.module.exports.CompositeDisposable (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:39:17627)
	at n (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:279)
	at Object.<anonymous> (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:35:14354)
	at n (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:279)
	at Object.<anonymous> (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:16944)
	at n (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:279)
	at Object.<anonymous> (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:45239)
	at n (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:279)
	at /home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:1078
	at Object.<anonymous> (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:1:1088)
	at Object.<anonymous> (/home/noxxious/.vscode/extensions/kiteco.kite-0.92.0/dist/kite-extension.js:41:3)
	at Module.t._initNodeRequire.o._compile (/opt/visual-studio-code/resources/app/out/vs/loader.js:15:804)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)
	at Function.t._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)
	at Function.t.getExtensionPathIndex.then.i._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/opt/visual-studio-code/resources/app/out/vs/loader.js:31:639)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:60
	at I._doActivateExtension (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:168)
	at I._activateExtension (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:762:6)
	at I.<anonymous> (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:868)
	at Generator.next (<anonymous>)
	at n (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:979)
	at new Promise (<anonymous>)
	at n (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:756)
	at Object.actualActivateExtension (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:570)
	at p._activateExtension (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:144)
	at define._activateExtensions.r.length.Promise.all.s.map.e (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:814)
	at Array.map (<anonymous>)
	at p._activateExtensions (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:802)
	at p._activateExtensions (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:861)
	at p.activateByEvent (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:635)
	at I._activateByEvent (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:680)
	at I._handleEagerExtensions (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:764:710)
	at define._startExtensionHost._readyToStartExtensionHost.wait.then.then (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:768:386)
	at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by metalogical** [comment]
Closed due to age. This should hopefully no longer be an issue.
